language: node_js
node_js:
  - '11'

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - yarn

script:
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
